id: PA5643F42
initial_creation_type: input
source_metadata:
  title: Kachöpa Series
  language: fr
  description: Prayers and Practices
  volume:
    79adcb6508234f838c1299422c6d4657:
      title: Raising the Windhorse
      parent: Prayers and Practices
created_at: '2022-03-01T00:09:28.226470'
last_modified_at: '2022-03-01T00:09:28.226473'
